import { NewsItem, NewsStats } from './types';

export const mockNewsItems: NewsItem[] = [
  {
    id: '1',
    source: 'MoneyControl',
    url: 'https://www.moneycontrol.com/news/business/markets/sensex-nifty-live-today-1.html',
    title: 'Sensex surges 500 points as banking stocks rally on RBI policy expectations',
    published_at: '2025-01-20T09:30:00Z',
    content: 'Indian benchmark indices rallied sharply on Monday with Sensex gaining over 500 points...',
    keyword_hits: ['Sensex', 'Banking', 'RBI'],
    ai_summary: 'Indian markets showed strong bullish momentum driven by banking sector gains ahead of the RBI monetary policy meeting. Key gainers include HDFC Bank, ICICI Bank, and SBI.',
    status: 'completed',
    created_at: '2025-01-20T09:35:00Z',
  },
  {
    id: '2',
    source: 'Economic Times',
    url: 'https://economictimes.com/markets/ipo/upcoming-ipo-2025.html',
    title: 'Upcoming IPOs 2025: Five companies set to raise ₹15,000 crore in January',
    published_at: '2025-01-19T14:20:00Z',
    content: 'The IPO market in India is expected to remain buoyant in 2025...',
    keyword_hits: ['IPO', 'Markets', 'Investment'],
    ai_summary: 'January 2025 will see a flurry of IPO activity with five major companies planning to raise ₹15,000 crore collectively. Key sectors include fintech and clean energy.',
    status: 'completed',
    created_at: '2025-01-19T14:25:00Z',
  },
  {
    id: '3',
    source: 'Reuters India',
    url: 'https://www.reuters.com/markets/asia/india-inflation-december-2025.html',
    title: 'India inflation eases to 5.2% in December, within RBI comfort zone',
    published_at: '2025-01-19T11:00:00Z',
    content: 'Consumer price inflation in India moderated to 5.2% in December...',
    keyword_hits: ['Inflation', 'RBI', 'Economy'],
    ai_summary: null,
    status: 'pending',
    created_at: '2025-01-19T11:05:00Z',
  },
  {
    id: '4',
    source: 'Bloomberg Quint',
    url: 'https://www.bloombergquint.com/business/tata-steel-expansion.html',
    title: 'Tata Steel announces ₹12,000 crore expansion plan for green steel production',
    published_at: '2025-01-18T16:45:00Z',
    content: 'Tata Steel Ltd unveiled an ambitious ₹12,000 crore investment plan...',
    keyword_hits: ['Steel', 'Tata', 'Green Energy', 'Manufacturing'],
    ai_summary: 'Tata Steel commits ₹12,000 crore to expand green steel production capacity, targeting carbon neutrality by 2045. The expansion will create 5,000 new jobs.',
    status: 'completed',
    created_at: '2025-01-18T16:50:00Z',
  },
  {
    id: '5',
    source: 'MoneyControl',
    url: 'https://www.moneycontrol.com/news/business/mutual-funds-inflows.html',
    title: 'Mutual funds see record ₹25,000 crore SIP inflow in December 2024',
    published_at: '2025-01-18T10:30:00Z',
    content: 'Systematic Investment Plans (SIPs) in mutual funds continued their strong run...',
    keyword_hits: ['Mutual Funds', 'SIP', 'Investment'],
    ai_summary: 'SIP inflows hit an all-time high of ₹25,000 crore in December 2024, reflecting growing retail investor confidence. Equity funds remain the preferred choice.',
    status: 'completed',
    created_at: '2025-01-18T10:35:00Z',
  },
  {
    id: '6',
    source: 'Livemint',
    url: 'https://www.livemint.com/market/crypto-regulation-india.html',
    title: 'Government mulls new crypto framework, clarity expected in Budget 2025',
    published_at: '2025-01-17T18:00:00Z',
    content: 'The finance ministry is working on a comprehensive cryptocurrency regulation...',
    keyword_hits: ['Crypto', 'Regulation', 'Budget'],
    ai_summary: null,
    status: 'processing',
    created_at: '2025-01-17T18:05:00Z',
  },
  {
    id: '7',
    source: 'Business Standard',
    url: 'https://www.business-standard.com/article/auto-sales-q3.html',
    title: 'Auto sector posts 15% YoY growth in Q3 FY25 on festive demand',
    published_at: '2025-01-17T12:15:00Z',
    content: 'The Indian automobile industry reported robust growth in the third quarter...',
    keyword_hits: ['Auto', 'Sales', 'Manufacturing'],
    ai_summary: 'Auto industry Q3 results show 15% year-on-year growth led by SUVs and electric vehicles. Maruti, Tata Motors, and Mahindra lead the pack.',
    status: 'completed',
    created_at: '2025-01-17T12:20:00Z',
  },
  {
    id: '8',
    source: 'CNBC TV18',
    url: 'https://www.cnbctv18.com/market/fii-flows-january.html',
    title: 'FIIs turn net buyers in January, pump in ₹8,500 crore so far',
    published_at: '2025-01-16T15:30:00Z',
    content: 'Foreign institutional investors have turned bullish on Indian equities...',
    keyword_hits: ['FII', 'Investment', 'Markets'],
    ai_summary: 'FIIs reverse their selling trend with net purchases of ₹8,500 crore in January. Technology and banking sectors attract maximum foreign interest.',
    status: 'completed',
    created_at: '2025-01-16T15:35:00Z',
  },
  {
    id: '9',
    source: 'Economic Times',
    url: 'https://economictimes.com/industry/banking/hdfc-bank-results.html',
    title: 'HDFC Bank Q3 results: Net profit rises 18% to ₹16,735 crore',
    published_at: '2025-01-16T09:00:00Z',
    content: 'HDFC Bank, India\'s largest private sector lender, reported an 18% rise in net profit...',
    keyword_hits: ['HDFC Bank', 'Banking', 'Earnings'],
    ai_summary: null,
    status: 'pending',
    created_at: '2025-01-16T09:05:00Z',
  },
  {
    id: '10',
    source: 'MoneyControl',
    url: 'https://www.moneycontrol.com/news/business/startups/startup-funding-2025.html',
    title: 'Indian startups raise $2.1 billion in first two weeks of 2025',
    published_at: '2025-01-15T14:45:00Z',
    content: 'The Indian startup ecosystem has kicked off 2025 on a strong note...',
    keyword_hits: ['Startups', 'Funding', 'Investment'],
    ai_summary: 'Indian startups show strong momentum with $2.1 billion raised in early January 2025. Fintech and AI sectors lead funding rounds.',
    status: 'completed',
    created_at: '2025-01-15T14:50:00Z',
  },
];

export const mockStats: NewsStats = {
  totalArticles: 1247,
  processedArticles: 1089,
  pendingArticles: 158,
  sourceBreakdown: {
    'MoneyControl': 342,
    'Economic Times': 298,
    'Reuters India': 187,
    'Bloomberg Quint': 156,
    'Livemint': 134,
    'Business Standard': 89,
    'CNBC TV18': 41,
  },
  keywordBreakdown: {
    'Markets': 423,
    'Banking': 312,
    'Investment': 278,
    'IPO': 189,
    'Startups': 156,
    'RBI': 134,
    'Economy': 98,
  },
};

export const availableSources = [
  'MoneyControl',
  'Economic Times',
  'Reuters India',
  'Bloomberg Quint',
  'Livemint',
  'Business Standard',
  'CNBC TV18',
];
