// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljfrmoifprsymqhhlzsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqZnJtb2lmcHJzeW1xaGhsenNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0Njk5MzgsImV4cCI6MjA4NDA0NTkzOH0.wOLR62n7bSSYpZdKbcO7J1BoNJrWoiONStHX8TqXJZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});